export const INVENTORY_REPOSITORY = 'INVENTORY_REPOSITORY';
export const INVENTORY_WRITE_REPOSITORY = 'INVENTORY_WRITE_REPOSITORY';
export const INVENTORY_READ_REPOSITORY = 'INVENTORY_READ_REPOSITORY';
export const INVENTORY_PRODUCT_READONLY = 'INVENTORY_PRODUCT_READONLY';
export const INVENTORY_AVAILABILITY_PORT = 'INVENTORY_AVAILABILITY_PORT';
export const INVENTORY_RESERVATION_PORT = 'INVENTORY_RESERVATION_PORT';

export default {
    INVENTORY_REPOSITORY,
    INVENTORY_WRITE_REPOSITORY,
    INVENTORY_READ_REPOSITORY,
    INVENTORY_PRODUCT_READONLY,
    INVENTORY_AVAILABILITY_PORT,
    INVENTORY_RESERVATION_PORT,
};
