export const ORDER_WRITE_REPOSITORY = 'ORDER_WRITE_REPOSITORY';
export const ORDER_READ_REPOSITORY = 'ORDER_READ_REPOSITORY';
export const ORDER_CART_READONLY = 'ORDER_CART_READONLY';
export const ORDER_PRODUCT_READONLY = 'ORDER_PRODUCT_READONLY';
export const ORDER_PRICING_SERVICE = 'ORDER_PRICING_SERVICE';
export const ORDER_STOCK_SERVICE = 'ORDER_STOCK_SERVICE';
export const ORDER_RESERVE_STOCK = 'ORDER_RESERVE_STOCK';
export const ORDER_PAYMENT_READ_PORT = 'ORDER_PAYMENT_READ_PORT';
export const ORDER_PAYMENT_WRITE_PORT = 'ORDER_PAYMENT_WRITE_PORT';
export const ORDER_PURCHASE_HISTORY_PORT = 'ORDER_PURCHASE_HISTORY_PORT';

export default {
    ORDER_WRITE_REPOSITORY,
    ORDER_READ_REPOSITORY,
    ORDER_CART_READONLY,
    ORDER_PRODUCT_READONLY,
    ORDER_PRICING_SERVICE,
    ORDER_STOCK_SERVICE,
    ORDER_RESERVE_STOCK,
    ORDER_PAYMENT_READ_PORT,
    ORDER_PAYMENT_WRITE_PORT,
    ORDER_PURCHASE_HISTORY_PORT,
};
