export const USER_READ_REPOSITORY = 'USER_READ_REPOSITORY';
export const USER_WRITE_REPOSITORY = 'USER_WRITE_REPOSITORY';
export const USER_READONLY = 'USER_READONLY';
export const USER_NOTIFICATION = 'USER_NOTIFICATION';
export const USER_VERIFICATION_PORT = 'USER_VERIFICATION_PORT';

export default {
    USER_READ_REPOSITORY,
    USER_WRITE_REPOSITORY,
    USER_READONLY,
    USER_NOTIFICATION,
    USER_VERIFICATION_PORT,
};
