export const PAYMENT_WRITE_REPOSITORY = 'PAYMENT_WRITE_REPOSITORY';
export const PAYMENT_READ_REPOSITORY = 'PAYMENT_READ_REPOSITORY';
export const PAYMENT_PROVIDER = 'PAYMENT_PROVIDER';
export const PAYMENT_ORDER_READONLY = 'PAYMENT_ORDER_READONLY';
export const PAYMENT_ORDER_WRITE = 'PAYMENT_ORDER_WRITE';

export default {
    PAYMENT_WRITE_REPOSITORY,
    PAYMENT_READ_REPOSITORY,
    PAYMENT_PROVIDER,
    PAYMENT_ORDER_READONLY,
    PAYMENT_ORDER_WRITE,
};
