export const REVIEW_READ_PORT = 'REVIEW_READ_PORT';
export const REVIEW_WRITE_PORT = 'REVIEW_WRITE_PORT';
export const AUTH_PORT = 'REVIEWS_AUTH_PORT';
export const USER_PORT = 'REVIEWS_USER_PORT';
export const PRODUCTS_PORT = 'REVIEWS_PRODUCTS_PORT';
export const ORDERS_PORT = 'REVIEWS_ORDERS_PORT';

export default {
    REVIEW_READ_PORT,
    REVIEW_WRITE_PORT,
    AUTH_PORT,
    USER_PORT,
    PRODUCTS_PORT,
    ORDERS_PORT,
};
