export const CART_READ_REPOSITORY = 'CART_READ_REPOSITORY';
export const CART_WRITE_REPOSITORY = 'CART_WRITE_REPOSITORY';
export const CART_PRICING_SERVICE = 'CART_PRICING_SERVICE';
export const CART_STOCK_SERVICE = 'CART_STOCK_SERVICE';
export const CART_SNAPSHOT_PORT = 'CART_SNAPSHOT_PORT';


export default {
    CART_READ_REPOSITORY,
    CART_WRITE_REPOSITORY,
    CART_PRICING_SERVICE,
    CART_STOCK_SERVICE,
    CART_SNAPSHOT_PORT,
};
