export const AUTH_USER_REPOSITORY = 'AUTH_USER_REPOSITORY';
export const AUTH_REFRESH_TOKEN_REPOSITORY = 'AUTH_REFRESH_TOKEN_REPOSITORY';
export const AUTH_TOKEN_SERVICE = 'AUTH_TOKEN_SERVICE';
export const AUTH_PASSWORD_HASHER = 'AUTH_PASSWORD_HASHER';
